version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - /var/www/html:/usr/share/nginx/html
    restart: always
  proclamation:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/proclamation
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver

  mysqlserver:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=proclamation
      - MYSQL_PASSWORD=proclamation
      - MYSQL_DATABASE=proclamation
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config: